services:
  - type: web
    name: license-watchdog-ui
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.address 0.0.0.0
    envVars:
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_PATH
        value: watchdog.db
